### ISSUE TITLE
Spy module syntax error on windows build

### ISSUE THREAD

**Issue by terencode** [vasyahuyasa/remod-sauerbraten#15]
Here is what is written on the log when a client connect with spy module enabled :
[2015-05-29 23:50:55] CONNECT Térence(0)(192.168.56.1)
[ERROR] Error in SQL query: UPDATE `spy` SET lastseen=, cnt=cnt+1 WHERE ip=-1062717439 AND name LIKE 'Térence'
[ERROR] near ",": syntax error

**Comment by vasyahuyasa** [comment]
fixed
