### ISSUE TITLE
Add nodamage command

### ISSUE THREAD

**Issue by terencode** [vasyahuyasa/remod-sauerbraten#18]
Only effective on edit, disallow players to kill others by removing damages.

**Comment by vasyahuyasa** [comment]
added #nodamage command

**Comment by Croydon** [comment]
@vasyahuyasa A small hint: If you write for example "close #18" in the respective commit, the issue #18 gets closed automatically as soon as the commit is pushed to the master branch. So people can see directly on the issue page in which commit it got fixed/added and you don't need to write another note :)

**Comment by vasyahuyasa** [comment]
@Croydon thanks, get it
