### ISSUE TITLE
Outsource windows libraries to src/libraries folder

### ISSUE THREAD

**Issue by Fohlen** [vasyahuyasa/remod-sauerbraten#2]
Please outsource any library (.dll) to the src/lib folder!

**Comment by Fohlen** [comment]
#3 should resolve this bug as well?!

**Comment by rmhmlhr** [comment]
Not really. For example, look at libsqlite3-0.dll . On linux it could ne resolved by install libsqlite from repository, but on windows it shoudl be provided as a separate library.

**Comment by Fohlen** [comment]
Well, it shouldn't be included in the source directory either. Better to use the release feature?!

**Comment by vasyahuyasa** [comment]
I move it after creating of release branch.

**Comment by Fohlen** [comment]
:+1:
