### ISSUE TITLE
Mute command should not display info message

### ISSUE THREAD

**Issue by terencode** [vasyahuyasa/remod-sauerbraten#22]
Remove the mute and unmute message from 'mute' command  and migrate it to cmd_mute.cfg and cmd_unmute.cfg as below :
cmd_mute = [
		mute $arg2 1
		say (format "^f7Player ^f2%1 ^f7has been ^f3muted ^f7by ^f6%2" (getname $arg2) 
                pm $arg2 "You have been muted."
(getname $arg1))
]
registercommand "mute" cmd_mute 2 "c" "mute [cn] ^f1Mute player"
cmd_unmute = [
		mute $arg2 1
		say (format "^f7Player ^f2%1 ^f7has been ^f3unmuted)
                pm $arg2 "You have been unmuted please be polite."
]
registercommand "unmute" cmd_unmute 2 "c" "unmute [cn] ^f1Mute player"

**Comment by terencode** [comment]
Nevermind you can change that easily by removing the message from messages.cfg.

**Comment by Fohlen** [comment]
Please use pull-requests to do these kind of requests

**Comment by terencode** [comment]
Ok thx Fohlen
