### ISSUE TITLE
Seperate code & binary releases

### ISSUE THREAD

**Issue by Fohlen** [vasyahuyasa/remod-sauerbraten#3]
Please integrate seperated code & binary releases.
You could use one binary branch (or seperate repo) to package stable binaries ..
Afterward's use git's release feature to release remod version.
For convention I would suggest you to use the following versioning scheme:
major.minor.bugfix

Major = essentiall new feature (may break backward-compatibility)
minor = new feature / fix (...)
bugfix = small code change

**Comment by rmhmlhr** [comment]
Agree, moving out binaries from repository is a good practice. Github release's feature is good enough, but it requres releases themselves. I think it's time remod had 0.1.0 :D

**Comment by vasyahuyasa** [comment]
Is git support automatic change of version number after commit? Change version number by hands before commits is boring. If i get how works release system on github i will do separating code and binaries.

**Comment by Fohlen** [comment]
https://developer.github.com/v3/repos/releases/
can do this.
