### ISSUE TITLE
Command #kick

### ISSUE THREAD

**Issue by temka32924** [vasyahuyasa/remod-sauerbraten#31]
if you write example #kick 0 5 test
command ban for 1 day and 22 hour

**Comment by Croydon** [comment]
There is already a #kick command. The only thing missing perhaps is a value for naming a reason.

**Comment by temka32924** [comment]
No, i mean what command #kick is broken. When you write #kick 0 5 test, you kicked player not in 5 minutes.

**Comment by mishantrop** [comment]
pidora

**Comment by Fohlen** [comment]
`kick <cn> (time) ^f1Kick and ban player for time` is what will occur to you when you type in `#help kick`
As for the commenting, it is possible via the `#ban` command @Croydon
