### ISSUE TITLE
Text Chat, Switch Teams "broken"

### ISSUE THREAD

**Issue by Fohlen** [vasyahuyasa/remod-sauerbraten#33]
Currently it happens to me that after a while neither the text chat can be used, nor switch team does work. I couldn't yet figure out how this is to be reproduced. Any further information I can give to you, let me know about it.
Thanks in advance!

**Comment by vasyahuyasa** [comment]
That problem happens after 24 days of server uptime, because of int overflow in that function https://github.com/vasyahuyasa/remod-sauerbraten/blob/master/src/mod/remod.cpp#L966 and all messages marked as flood.

**Comment by nymsauer** [comment]
Isn't this a problem with enet? As far as I can tell, the server uses [`enet_time_get`](http://enet.bespin.org/unix_8c.html#a26eeed004fe8fa39b0fb5b18efbd4d64) to keep time, which returns the walltime in milliseconds in an `enet_uint32` (`unsigned int`), which would overflow within less than 50 days of setting `enet_time_set(0)` even without casting it to `int`.

**Comment by vasyahuyasa** [comment]
Close because flood protection is disabled at unil good solutionn will be found.
