### ISSUE TITLE
Segfault with latest master

### ISSUE THREAD

**Issue by nayavu** [vasyahuyasa/remod-sauerbraten#34]
rb1 failed to update (rb2 and rb0 work fine, though)
Last remod from master (previous version ~Oct 2016 worked fine).
gdb output: https://gist.github.com/nayavu/a5c6fb21ccc6bec991ac3425460d10f4
server-init.cfg: https://gist.github.com/nayavu/70ca940b3942f299bcb533e24a3f4485

$ uname -a
`Linux scserver 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux`

**Comment by vasyahuyasa** [comment]
Looks like parameter count mistmatch on this line
https://github.com/vasyahuyasa/remod-sauerbraten/blob/b19adf5f5d64959c0503b171561230ec0e63f3ca/src/mod/irc.cpp#L591
format string expect 9 but 8 passed

2017-04-12 23:53 GMT+03:00 Oramah <notifications@github.com>:

**Comment by vasyahuyasa** [comment]
Should be fixed with commit dcb6b82b5183225eab5862f17bcb7d91a555bc33, but need to test it.

**Comment by ivelichko** [comment]
Yes, it's been fixed. Good job

**Comment by nayavu** [comment]
Yes, it's been fixed. Good job!
