### ISSUE TITLE
Savemap & Loadmap dont working.

### ISSUE THREAD

**Issue by SalatielSauer** [vasyahuyasa/remod-sauerbraten#39]
```
// save map to local file system
cmd_savemap = [
	savemap $arg2
]

registercommand "savemap" cmd_savemap 3 "s" "savemap [name] ^f1Save map to local file system (coopedit only)"
```
```
// upload map from local file system
cmd_loadmap = [
	loadmap $arg2
]

registercommand "loadmap" cmd_loadmap 3 "s" "loadmap [name] ^f1Upload map to server from local file system (coopedit only)"
```

Savemap *name* is showing the following error:
[No map to save]

Loadmap *name* is showing the following error:
[failed to open, map dont exist on the server]

**Comment by SalatielSauer** [comment]
hmm, the last update of this was 6 years ago, so... maybe never will work.

**Comment by Fohlen** [comment]
You should check out @inexorgame, similiar functionality exists

**Comment by vasyahuyasa** [comment]
`#savemap` works only in coop mode, before save map to hard disk you need to upload it on server with `/sendmap` command. You did it before `#savemap`?

**Comment by SalatielSauer** [comment]
@vasyahuyasa I had not sent the map before the #savemap, thank you so much. And nice work with the Remod!

**Comment by SalatielSauer** [comment]
Since this topic is open, I'll ask another question: Is there a way to cancel the **forceintermission** after (or during) intermission? I have this question, because if i change the map during the intermission (using the **loadmap**) the intermission still continues, and change to another mode soon after...
