### ISSUE TITLE
$arg1 recognizing only cn 0

### ISSUE THREAD

**Issue by SalatielSauer** [vasyahuyasa/remod-sauerbraten#40]
I noticed that i was having this problem when i received messages that were to be sent in PM to someone else. See the images and my code below...

```
onconnect_chainsawctf = [
if (= $func_chainsawctf 1)[
		asleep 1000 [
			pm $arg1 (format "^f0ChainsawCTF Mode is enabled")
			
			asleep 500 [
				say (format "^f3[ChainsawCTF]: ^f0REMEMBER: ^f1This is the ChainSaw Mode, Rifle dont work here.")
			]
		]
	]
]
delhandler onconnect onconnect_chainsawctf
addhandler onconnect onconnect_chainsawctf
```

the pm message is only sent to the client at a 0 num, whenever a player enters server.
https://i.imgur.com/LXGtxBS.png

https://i.imgur.com/d2qbJk9.png

the $arg1 worked fine since a time ago (not that same script, but others). I have no idea how it can be reproduced, in recent days I have only modified line 3320 in server.cpp to spectate bots:
```
case N_SPECTATOR:
            {
                int spectator = getint(p), val = getint(p);
                if(!ci->privilege && !ci->local && (spectator!=sender || (ci->state.state==CS_SPECTATOR && mastermode>=MM_LOCKED))) break;
                clientinfo *spinfo = getinfo(spectator); // no bots
                if(!spinfo || !spinfo->connected || (spinfo->state.state==CS_SPECTATOR ? val : !val)) break;

                if(spinfo->state.state!=CS_SPECTATOR && val) forcespectator(spinfo);
                else if(spinfo->state.state==CS_SPECTATOR && !val) unspectate(spinfo);

                if(cq && cq != ci && cq->ownernum != ci->clientnum) cq = NULL;

                // remod
                remod::onevent(ONSPECTATOR, "ii", spectator, val ? 1 : 0);

                break;
            }
```
I do not know exactly when this started happening...

**Comment by vasyahuyasa** [comment]
Problem can be in `asleep 1000 ` before that function will be executed 
`$arg1` can be changed by some other function, try to replace $arg1 with 
@arg1 or something like that. Good cubescript manual is here 
https://github.com/Hirato/lamiae/wiki/CubeScript#lookups

**Comment by SalatielSauer** [comment]
Oh, this @arg1 worked fine, thanks again.
