### ISSUE TITLE
banmanager::getbanlist passes null pointer to strcmp

### ISSUE THREAD

**Issue by nymsauer** [vasyahuyasa/remod-sauerbraten#43]
`banmanager::getbanlist` passes a null pointer to `strcmp` if the name parameter is provided, because the first list in banlists is the local banlist with `name = NULL`. 
```
banlist::banlist()
{
    name = NULL;
}
```
```
banmanager::banmanager()
{
    // create local banlist
    banlist *bl = new banlist;
    banlists.add(bl);
}
```
```
banlist* banmanager::getbanlist(char *name)
{
    banlist *bl = NULL;
    if(name && name[0])
    {
        loopv(banlists)
            if(strcmp(banlists[i]->name, name))
            {
                bl = banlists[i];
                break;
            }
    }
    else bl = banlists[0]; // local banlist without name
    if(bl == NULL) bl = new banlist(name); // create new banlist
    return bl;
}
```

In the current remod release this is not noticeable because getbanlist is always called with no name provided, but if for example line 175 in remod.cpp is changed to
```
bm->addban("pbans", ip, mask, 0, time(0), "server", reason);
```
then trying to add a ban causes a segfault for me.

**Comment by Fohlen** [comment]
@nymsauer mind creating a PR to fix this, then I will merge

**Comment by vasyahuyasa** [comment]
Realease tag will be added a bit later
