### ISSUE TITLE
getpos is not updated on spawn

### ISSUE THREAD

**Issue by SalatielSauer** [vasyahuyasa/remod-sauerbraten#46]
Hi, the **onspawn** event does not updated the **getpos** value, returning only the position of the player's death, and not the spawn position. I believe this is something unexpected...

How to reproduce:
```
x = [say (getpos $arg1)]

addhandler "onspawn" x
```

**Comment by vasyahuyasa** [comment]
Hello, thanks for report, i'll check for fix.

**Comment by vasyahuyasa** [comment]
Issue should be fixed now
