### ISSUE TITLE
Feature Request: add support for additional auth servers

### ISSUE THREAD

**Issue by sauerbraten** [vasyahuyasa/remod-sauerbraten#74]
I would like to get my [patch that adds support for third-party auth servers](https://github.com/sauerbraten/p1xbraten/blob/main/patches/authservers.patch) included in remod; is this something you would be interested in? The linked patch is written against the vanilla code base, but I'm happy to send a PR targeting remod's master branch.

(Third-party auth servers are master servers other than master.sauerbraten.org that are used solely to authenticate players. A patched server doesn't `regserv` with them and they can't set gbans etc.)

I have a test server (patched vanilla) and auth server (custom auth-only master with user registration via Discord) set up and had a few people test this patch already. Feel free to PM me (p1x) on Discord if you'd like to try it out!

**Comment by vasyahuyasa** [comment]
I would like to include that patch but i want to rework it a bit. Do not modify current code but put it in separate file and call it like
```cpp
remod::processauthserverinput(...)
```

**Comment by vasyahuyasa** [comment]
When i get some free time i will add it
